### ISSUE TITLE
TYUT测试失败

### ISSUE THREAD

**Issue by zhanghua000** [ZimoLoveShuang/auto-sign#17]
返回数据如下：
```
Traceback (most recent call last):
  File "/var/user/index.py", line 324, in main_handler
    raise e
  File "/var/user/index.py", line 322, in main_handler
    main()
  File "/var/user/index.py", line 312, in main
    params = getUnSignedTasks(session, apis)
  File "/var/user/index.py", line 144, in getUnSignedTasks
    if len(res.json()['datas']['unSignedTasks']) &lt; 1:
  File "/opt/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/var/lang/python3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/var/lang/python3/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/lang/python3/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
同样的账户数据在`auto-submit`项目中可以正常使用
执行日志如下：
```
START RequestId: 269c399c-0b65-4bdc-a5b4-0669ef369fe1

Event RequestId: 269c399c-0b65-4bdc-a5b4-0669ef369fe1

Starting new HTTPS connection (1): www.cpdaily.com:443

https://www.cpdaily.com:443 "GET /v6/config/guest/tenant/list HTTP/1.1" 200 None

Starting new HTTPS connection (1): www.cpdaily.com:443

https://www.cpdaily.com:443 "GET /v6/config/guest/tenant/info?ids=tyut HTTP/1.1" 200 None

Starting new HTTPS connection (1): tyut.campusphere.net:443

https://tyut.campusphere.net:443 "GET / HTTP/1.1" 302 154

https://tyut.campusphere.net:443 "GET /portal/index.html HTTP/1.1" 200 None

2020-10-30 13:18:44 {'login-url': 'https://tyut.campusphere.net/iap/login?service=https%3A%2F%2Ftyut.campusphere.net%2Fportal%2Flogin', 'host': 'tyut.campusphere.net'}

Starting new HTTP connection (1): www.zimo.wiki:8080

http://www.zimo.wiki:8080 "POST /wisedu-unified-login-api-v1.0/api/login HTTP/1.1" 200 None

2020-10-30 13:18:45 acw_tc=2f624a0616040351251098055e6b82ffebb10480388cb8daff6bdeb820f5ad;CONVERSATION=iap-1018615872508040-CONV-46fa580b-0c20-402b-9075-6ad6a0f789a1;CASTGC=iap-1018615872508040-TGT-30339081-bc8c-4590-88f1-df0785919e47;MOD_AUTH_CAS=ST-iap:1018615872508040:ST:5979e453-7258-492a-af00-c55dc5f9e730:20201030131845

Starting new HTTPS connection (1): tyut.campusphere.net:443

https://tyut.campusphere.net:443 "POST /wec-counselor-sign-apps/stu/sign/getStuSignInfosInOneDay HTTP/1.1" 404 710

https://tyut.campusphere.net:443 "POST /wec-counselor-sign-apps/stu/sign/getStuSignInfosInOneDay HTTP/1.1" 404 710


END RequestId: 269c399c-0b65-4bdc-a5b4-0669ef369fe1

Report RequestId: 269c399c-0b65-4bdc-a5b4-0669ef369fe1 Duration:2248ms Memory:128MB MemUsage:59.2383MB
```

**Comment by mrjesen** [comment]
巧了我也是

**Comment by Mysels** [comment]
接口换了 看我pr 集合了@meethigher 抓的新接口

**Comment by zhanghua000** [comment]
> 接口换了 看我pr 集合了@meethigher 抓的新接口

感谢大佬，经测试已恢复
