### ISSUE TITLE
提供一个文本 TypeError: must be str, not float 解决方案

### ISSUE THREAD

**Issue by 1154450477** [ZimoLoveShuang/auto-sign#25]
希望大佬提供解决思路

**Comment by 1154450477** [comment]
Traceback (most recent call last): File "/var/user/index.py", line 381, in main_handler raise e File "/var/user/index.py", line 358, in main_handler form = fillForm(session, params['form'], apis['host']) File "/var/user/index.py", line 203, in fillForm log('答案%d：' % sort + formItem['value']) TypeError: must be str, not float #25

**Comment by 1154450477** [comment]
必须传入的是字符序列,不能是数字序列 在数字前后加入" 
如：
value: "36.5"
