### ISSUE TITLE
KeyError: 'cookies'

### ISSUE THREAD

**Issue by SWERecker** [ZimoLoveShuang/auto-sign#36]
```
Traceback (most recent call last):
  File "index.py", line 349, in <module>
    print(main_handler({}, {}))
  File "index.py", line 342, in main_handler
    raise e
  File "index.py", line 340, in main_handler
    main()
  File "index.py", line 333, in main
    session = getSession(user, apis)
  File "index.py", line 116, in getSession
    cookieStr = str(res.json()['cookies'])
KeyError: 'cookies'
```

API似乎失效了
`{'timestamp': '2020-12-30T00:50:35.882+00:00', 'status': 500, 'error': 'Internal Server Error', 'message': '', 'path': '/wisedu-unified-login-api-v1.0/api/login'}`

**Comment by jiiiiiiiiiin** [comment]
自己部署一下作者的这个模拟登陆服务就可以了 [`wisedu-unified-login-api`](https://github.com/ZimoLoveShuang/wisedu-unified-login-api)

**Comment by fishUPs** [comment]
请问这个问题怎么解决，我已经在本地部署了这个模拟登录api，该怎么修改index.py的内容呢
