### ISSUE TITLE
通用流程下执行login.py遇到的问题

### ISSUE THREAD

**Issue by fishUPs** [ZimoLoveShuang/auto-sign#50]
2021-07-15 23:55:06 {'tenantId': 'ahjzu', 'login-url': 'xxxxx(链接点进去直接就是我的金指教育品台了，所以不展示了', 'host': 'ahjzu.campusphere.net'}
2021-07-15 23:55:06 正在获取验证码。。。
2021-07-15 23:55:06 验证码发送失败

求救

**Comment by fishUPs** [comment]
目前已做：
已经改了cpdaily的网址
已经改了des的密匙
这个报错里面的ampurl似乎是https://mobile.campushoy.com/v6/config/guest/tenant/list中没有的元素？那怎么引用的？求大佬告知

**Comment by fishUPs** [comment]
2021-07-15 23:39:36 正在获取验证码。。。
Traceback (most recent call last):
  File "D:\GGDownloads\auto-sign-master\auto-sign-master\currency\login.py", line 317, in <module>
    login()
  File "D:\GGDownloads\auto-sign-master\auto-sign-master\currency\login.py", line 297, in login
    getMessageCode()
  File "D:\GGDownloads\auto-sign-master\auto-sign-master\currency\login.py", line 146, in getMessageCode
    errMsg = res.json()['errMsg']
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
获取验证码发生报错，
求救

**Comment by fishUPs** [comment]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='sso.ahjzu.edu.cn', port=80): Max retries exceeded with url: /sso/login?service=http%3A%2F%2Fehall.ahjzu.edu.cn%2Famp-auth-adapter%2FloginSuccess%3FsessionToken%3D28d2d51e257a4fd48ae699f4b2ad1ee8 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017E78DD1190>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接 
的主机没有反应，连接尝试失败。'))

再次运行login后多了这个报错
