### ISSUE TITLE
请问这个问题如何处理

### ISSUE THREAD

**Issue by hiyuey3** [ZimoLoveShuang/auto-sign#52]
Traceback (most recent call last):
  File "/Users/cnyue/Git/auto-submit/index.py", line 388, in <module>
    print(main_handler({}, {}))/Users/cnyue/Git/auto-submit/generate.py
  File "/Users/cnyue/Git/auto-submit/index.py", line 381, in main_handler
    raise e
  File "/Users/cnyue/Git/auto-submit/index.py", line 347, in main_handler
    session = getSession(user, apis['login-url'])
  File "/Users/cnyue/Git/auto-submit/index.py", line 109, in getSession
    cookieStr = str(res.json()['cookies'])
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by hiyuey3** [comment]
发错地方了
